# Generated by Django 4.2.3 on 2023-07-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='id_articulo',
            new_name='articulo',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='id_usuario',
            new_name='usuario',
        ),
    ]
