# Generated by Django 4.2.3 on 2023-07-27 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Comentarios', '0003_alter_comentario_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha_edicion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
