# Generated by Django 4.2.3 on 2023-07-31 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comentarios', '0005_alter_comentario_fecha_edicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='contenido',
        ),
        migrations.AddField(
            model_name='comentario',
            name='texto',
            field=models.TextField(default='hola'),
            preserve_default=False,
        ),
    ]
