# Generated by Django 4.2.3 on 2023-07-31 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comentarios', '0006_remove_comentario_contenido_comentario_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(verbose_name='Comentario'),
        ),
    ]
