# Generated by Django 4.2.3 on 2023-07-25 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='id_articulo',
        ),
    ]
