# Generated by Django 4.2.3 on 2023-07-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('CO', 'Colaborador'), ('MI', 'Miembro')], default='MI', max_length=2),
        ),
    ]
