# Generated by Django 4.2.3 on 2023-07-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='portada'),
        ),
    ]
