# Generated by Django 4.2.3 on 2023-07-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0003_alter_articulo_imagen_portada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='id_categoria',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='id_usuario',
            new_name='usuario',
        ),
    ]
